package com.saurabhtotey.portfoliowebsite.data

import com.google.gson.Gson
import org.springframework.core.io.ClassPathResource
import java.util.*

/**
 * The class that represents an actual interest
 */
data class Interest(val name: String, val image: String, val description: String)

/**
 * The class that represents a category of interests
 * All members and fields were autogenerated
 */
data class InterestCategory(val category: String, val description: String, val items: Array<Interest>) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        other as InterestCategory
        if (category != other.category) return false
        if (description != other.description) return false
        if (!Arrays.equals(items, other.items)) return false
        return true
    }
    override fun hashCode(): Int {
        var result = category.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + Arrays.hashCode(items)
        return result
    }
}

//A variable of all the loaded interests from the config file as a list of InterestCategories
val interests: Array<InterestCategory> = Gson().fromJson(ClassPathResource("interests.json").file.inputStream().bufferedReader().use { it.readText() }, Array<InterestCategory>::class.java)
